### ISSUE TITLE
Implement internal hom objects for Day?

### ISSUE THREAD

**Issue by paf31** [ekmett/kan-extensions#27]
`Day` gives a symmetric closed category over functors, and the internal hom objects are relatively easy to express in Haskell. Here's a sketch in my PureScript repo, but I could send a PR if you're interested in adding these?

https://pursuit.purescript.org/packages/purescript-day/3.0.0/docs/Data.Functor.Day#t:Hom

**Comment by paf31** [comment]
Actually, it appear this is just `CoT` in disguise. Perhaps it would be better to just write the evaluation and composition functions for `CoT` instead:

```haskell
eval :: Day (CoT w m) w a -> m a
compose :: Day (CoT g h) (CoT f g) a -> CoT f h a
```

**Comment by ekmett** [comment]
Interestingly it was this thing that made me start thinking about Day in the first place.

**Comment by ekmett** [comment]
(That and Gershom bugging me to figure out what Day convolution would mean in Haskell)

**Comment by paf31** [comment]
Actually, I got this wrong, they're not quite the same.`CoT w m` has an extra `m` inside the `w` on the left:

```haskell
newtype CoT w m a = CoT { runCoT :: forall r. w (a -> m r) -> m r }

newtype Hom w m a = CoT { runCoT :: forall r. w (a -> r) -> m r }
``` 

and `CoT w m` is a `Monad` for any `Comonad w`, whereas `Monad (Hom w m)` also needs `Monad m`.

**Comment by ekmett** [comment]
Yep. I made a similar mistake connecting Day with Rift.

**Comment by ekmett** [comment]
there it fails to be an isomorphism without a something being a left adjoint.
