### ISSUE TITLE
Levity polymorphic codensity

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/kan-extensions#48]
I doubt this will get accepted, but it's worth noting that `Codensity` (and similar data types) can be made levity polymorphic

```haskell
newtype Codensity (m::TYPE rep -> Type) a = Codensity
  { runCodensity :: forall b. (a -> m b) -> m b
  }
```

If it's worth adding I'll make PR, if I understand correctly it can even be given a kind?

```haskell
Codensity :: (TYPE rep -> TYPE rep') -> (TYPE rep'' -> Type)
```

**Comment by RyanGlScott** [comment]
This was implemented in https://github.com/ekmett/kan-extensions/pull/52.
